// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgievcbjuaenyofkdmgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaWV2Y2JqdWFlbnlvZmtkbWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTQ3MzgsImV4cCI6MjA2MDIzMDczOH0.ob44vZsX9pyRnT3CZ6ZYTUTX7hT9y9Cq3NEigrjMtf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);